sudo: false
group: travis_latest
language: node_js
node_js: 9.11.1
before_install: npm i -g greenkeeper-lockfile
before_script:
- npm run ci-init
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
branches:
  except:
  - gh-pages
notifications:
  email:
    on_failure: change
