language: node_js
node_js: stable
install:
- npm i --no-save
before_script:
- npm run ci-init
after_success: npm run coverage
branches:
  except:
  - gh-pages
notifications:
  email:
    on_failure: change
