sudo: false
language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_a56afc9f0968_key -iv $encrypted_a56afc9f0968_iv
  -in secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
install:
- npm i --no-save
after_success: npm run coverage
branches:
  except:
  - gh-pages
notifications:
  email:
    on_failure: change
