language: node_js
node_js: stable
install:
- npm i --no-save
before_script:
- echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\n' > .transifexrc
after_success: npm run coverage
branches:
  except:
  - gh-pages
notifications:
  email:
    on_failure: change
